var expect = require('chai').expect,
    fs = require('fs-extra'),
    path = require('path'),
    Parser = require('../../lib/parser.js');

describe('Parser', function(){

  describe('parsing methods', function() {
    var parser = new Parser(),
        exampleFilePath = path.join(__dirname, '../fixtures/example.html'),
        styleFilePath = path.join(__dirname, '../fixtures/style.sass'),
        parsingFilePath = path.join(__dirname, '../fixtures/parse_input.html'),
        parsingContents = fs.readFileSync(parsingFilePath, 'utf8'),
        emptyContents = '';

    before(function() {
      parser.setStyleFilePath(styleFilePath)
            .setExampleFilePath(exampleFilePath);
    });


    describe('#parseName', function() {
      it('should parse the name correctly', function() {
        expect(parser.parseName(parsingContents)).to.equal('component-name-1');
      });

      it('should return empty in case of blank input', function() {
        expect(parser.parseName(emptyContents)).to.be.empty;
      });
    });

    describe('#parseDescription', function() {
      it('should parse the description correctly', function() {
        expect(parser.parseDescription(parsingContents)).to.equal('I am an awesome component 1.');
      });

      it('should return empty in case of blank input', function() {
        expect(parser.parseDescription(emptyContents)).to.be.empty;
      });
    });

    describe('#parseVariants', function() {
      it('should parse the variants correctly', function() {
        expect(parser.parseVariants(parsingContents)).to.have.length(3);
        expect(parser.parseVariants(parsingContents)).to.include('primary', 'default', 'secondary');
      });

      it('should return empty in case of blank input', function() {
        expect(parser.parseVariants(emptyContents)).to.be.empty;
      });
    });

    describe('#parseHTMLExample', function() {
      it('should parse the HTML correctly', function() {
        expect(parser.parseHTMLExample('component-name-1')).to.be.eq('\n<div class="component-name-1"></div>\n');
      });

      it('should return empty in case of blank input', function() {
        expect(parser.parseHTMLExample(emptyContents)).to.be.empty;
      });
    });

    describe('#parseJSExample', function() {
      it('should parse the JS correctly', function() {
        expect(parser.parseJSExample('component-name-1')).to.be.eq('\ndocument.write("Example Script")\n');
      });

      it('should return empty in case of blank input', function() {
        expect(parser.parseJSExample(emptyContents)).to.be.empty;
      });
    });
  });

  describe('#getComponents', function() {
    var parser = new Parser(),
        exampleFilePath = path.join(__dirname, '../fixtures/example.html'),
        styleFilePath = path.join(__dirname, '../fixtures/style.sass'),
        emptyStyleFilePath = path.join(__dirname, '../fixtures/empty_style.sass');

    context('when there are components ', function() {

      before(function() {
        parser.setStyleFilePath(styleFilePath)
              .setExampleFilePath(exampleFilePath)
              .run();
      });

      it('returns the components generated by running the parser #run)', function() {
        expect(parser.getComponents()).to.have.length(1);
      });
    });

    context('when there are no components ', function() {

      before(function() {
        parser.setStyleFilePath(emptyStyleFilePath)
              .setExampleFilePath(exampleFilePath)
              .run();
      });

      it('returns empty', function() {
        expect(parser.getComponents()).to.be.empty;
      });
    });
  });

  describe('#run', function() {
    var parser = new Parser(),
        exampleFilePath = path.join(__dirname, '../fixtures/example.html'),
        styleFilePath = path.join(__dirname, '../fixtures/style.sass');

    before(function() {
        parser.setStyleFilePath(styleFilePath)
              .setExampleFilePath(exampleFilePath);
    });

    it('generates the components', function() {
      expect(parser.run().getComponents()).to.have.length(1);
    });

    it('does not append the components when called multiple times', function() {
      parser.run();
      parser.run();
      expect(parser.getComponents()).to.have.length(1);
    });
  });
});
